/** IPC channel names shared by main and preload. */
export const CH = {
  getConnection: 'sentient:get-connection',
  getBackendStatus: 'sentient:get-backend-status',
  backendStatus: 'sentient:backend-status',
  restartBackend: 'sentient:restart-backend',
  openExternal: 'sentient:open-external',
  openPath: 'sentient:open-path',
  showNotification: 'sentient:show-notification',
  setLaunchAtLogin: 'sentient:set-launch-at-login',
  getLaunchAtLogin: 'sentient:get-launch-at-login',
  syncPrefs: 'sentient:sync-prefs',
  command: 'sentient:command',
  winMinimize: 'sentient:window-minimize',
  winMaximize: 'sentient:window-maximize',
  winClose: 'sentient:window-close',
  winIsMaximized: 'sentient:window-is-maximized',
  winMaximizedChanged: 'sentient:window-maximized-changed',
  getVersion: 'sentient:get-version',
  readyForScreenshot: 'sentient:ready-for-screenshot',
  pickFiles: 'sentient:pick-files',
  isFocused: 'sentient:is-focused',
  openFile: 'sentient:open-file',
  getDevicePrivacy: 'sentient:get-device-privacy',
  setDevicePrivacy: 'sentient:set-device-privacy',
  captureNotice: 'sentient:capture-notice',
  getDesktopNodeState: 'sentient:get-desktop-node-state',
  desktopNodeState: 'sentient:desktop-node-state',
  setAlwaysListening: 'sentient:set-always-listening',
  getAlwaysListening: 'sentient:get-always-listening',
  alwaysListeningChanged: 'sentient:always-listening-changed',
  wakeDetected: 'sentient:wake-detected'
} as const
