import json5
from .config import ALLOWED_MONGO_OPERATIONS, ALLOWED_COLLECTIONS, MEMORY_CATEGORIES

def validate_and_sanitize_query(llm_generated_json: str, user_id: str) -> dict:
    """
    Validates the query generated by the LLM. This is a critical security layer.
    - Parses the JSON.
    - Checks for allowed operations and collections.
    - Injects the user_id into the query to enforce multitenancy.
    - Validates memory category on insertion.
    """
    try:
        query_spec = json5.loads(llm_generated_json)
    except Exception as e:
        raise ValueError(f"Invalid JSON5 format: {e}")

    # 1. Check for required top-level keys
    required_keys = ['operation', 'collection', 'query']
    if not all(key in query_spec for key in required_keys):
        raise ValueError("Generated query missing one of 'operation', 'collection', 'query'.")

    op = query_spec['operation']
    coll = query_spec['collection']
    query = query_spec['query']

    # 2. Whitelist operation and collection
    if op not in ALLOWED_MONGO_OPERATIONS:
        raise SecurityException(f"Disallowed operation: {op}")
    if coll not in ALLOWED_COLLECTIONS:
        raise SecurityException(f"Disallowed collection access: {coll}")

    # 3. Enforce Multitenancy (MOST IMPORTANT)
    if op in ['find', 'update_one', 'delete_one']:
        if 'filter' not in query:
            query['filter'] = {}
        # Force user_id into the filter to prevent cross-tenant access
        query['filter']['user_id'] = user_id
    elif op == 'insert_one':
        if 'document' not in query:
            raise ValueError("Insert operation missing 'document'.")
        # Force user_id into the document
        query['document']['user_id'] = user_id
        
        # 4. Additional validation for insertions
        doc = query['document']
        if 'category' in doc and doc['category'] not in MEMORY_CATEGORIES:
            raise ValueError(f"Invalid memory category: {doc['category']}. Must be one of {MEMORY_CATEGORIES}")

    print(f"Validated Query for user '{user_id}': {op} on {coll} with {query}")
    return query_spec

class SecurityException(Exception):
    pass
