# src/client/docker-compose.yaml

services:
    sentient-client:
        build:
            context: .
            args:
                - NEXT_PUBLIC_APP_SERVER_URL=${NEXT_PUBLIC_APP_SERVER_URL}
                - NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}
                - AUTH0_SECRET=${AUTH0_SECRET}
                - APP_BASE_URL=${APP_BASE_URL}
                - NEXT_PUBLIC_APP_BASE_URL=${NEXT_PUBLIC_APP_BASE_URL}
                - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
                - AUTH0_DOMAIN=${AUTH0_DOMAIN}
                - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
                - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
                - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
                - AUTH0_SCOPE=${AUTH0_SCOPE}
                - MONGO_URI=${MONGO_URI}
                - MONGO_DB_NAME=${MONGO_DB_NAME}
                - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
                - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
                - NEXT_PUBLIC_AUTH0_NAMESPACE=${NEXT_PUBLIC_AUTH0_NAMESPACE}
                - NEXT_PUBLIC_LANDING_PAGE_URL=${NEXT_PUBLIC_LANDING_PAGE_URL}
                - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
                - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
                - VAPID_ADMIN_EMAIL=${VAPID_ADMIN_EMAIL}
        container_name: sentient-client
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - .env